command_timeout = 1000

[character] 
# https://starship.rs/config/#character
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"

[git_status]
# https://starship.rs/config/#git-status
stashed = 'ğŸ“¦'
modified = 'ğŸ“'

[directory]
truncation_length = 3

[gcloud]
# https://starship.rs/ja-jp/config/#google-cloud-gcloud
# å¸¸ã«è¡¨ç¤ºã•ã‚Œã¦ã—ã¾ã†ãŸã‚
disabled = true

[aws]
# https://starship.rs/ja-jp/config/#aws
# å¸¸ã«è¡¨ç¤ºã•ã‚Œã¦ã—ã¾ã†ãŸã‚
disabled = true
